# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import EremApi_pb2 as EremApi__pb2


class EremApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getHelloMsg = channel.unary_unary(
                '/EremApi/getHelloMsg',
                request_serializer=EremApi__pb2.Void.SerializeToString,
                response_deserializer=EremApi__pb2.HelloText.FromString,
                )
        self.getArray = channel.unary_unary(
                '/EremApi/getArray',
                request_serializer=EremApi__pb2.Void.SerializeToString,
                response_deserializer=EremApi__pb2.StringArray.FromString,
                )


class EremApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getHelloMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EremApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getHelloMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.getHelloMsg,
                    request_deserializer=EremApi__pb2.Void.FromString,
                    response_serializer=EremApi__pb2.HelloText.SerializeToString,
            ),
            'getArray': grpc.unary_unary_rpc_method_handler(
                    servicer.getArray,
                    request_deserializer=EremApi__pb2.Void.FromString,
                    response_serializer=EremApi__pb2.StringArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EremApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EremApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getHelloMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EremApi/getHelloMsg',
            EremApi__pb2.Void.SerializeToString,
            EremApi__pb2.HelloText.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EremApi/getArray',
            EremApi__pb2.Void.SerializeToString,
            EremApi__pb2.StringArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
