# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EremApi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rEremApi.proto\"\x1a\n\tHelloText\x12\r\n\x05hello\x18\x01 \x01(\t\"\x1b\n\x0bStringArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"\x06\n\x04Void2P\n\x07\x45remApi\x12\"\n\x0bgetHelloMsg\x12\x05.Void\x1a\n.HelloText\"\x00\x12!\n\x08getArray\x12\x05.Void\x1a\x0c.StringArray\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EremApi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOTEXT._serialized_start=17
  _HELLOTEXT._serialized_end=43
  _STRINGARRAY._serialized_start=45
  _STRINGARRAY._serialized_end=72
  _VOID._serialized_start=74
  _VOID._serialized_end=80
  _EREMAPI._serialized_start=82
  _EREMAPI._serialized_end=162
# @@protoc_insertion_point(module_scope)
