# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import EremApi_pb2 as EremApi__pb2


class EremApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSuggestions = channel.unary_unary(
                '/EremApi/getSuggestions',
                request_serializer=EremApi__pb2.CandidateUpdate.SerializeToString,
                response_deserializer=EremApi__pb2.Suggestions.FromString,
                )
        self.setSentence = channel.unary_unary(
                '/EremApi/setSentence',
                request_serializer=EremApi__pb2.Sentence.SerializeToString,
                response_deserializer=EremApi__pb2.Void.FromString,
                )
        self.isReady = channel.unary_unary(
                '/EremApi/isReady',
                request_serializer=EremApi__pb2.Void.SerializeToString,
                response_deserializer=EremApi__pb2.Ready.FromString,
                )


class EremApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setSentence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EremApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.getSuggestions,
                    request_deserializer=EremApi__pb2.CandidateUpdate.FromString,
                    response_serializer=EremApi__pb2.Suggestions.SerializeToString,
            ),
            'setSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.setSentence,
                    request_deserializer=EremApi__pb2.Sentence.FromString,
                    response_serializer=EremApi__pb2.Void.SerializeToString,
            ),
            'isReady': grpc.unary_unary_rpc_method_handler(
                    servicer.isReady,
                    request_deserializer=EremApi__pb2.Void.FromString,
                    response_serializer=EremApi__pb2.Ready.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EremApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EremApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EremApi/getSuggestions',
            EremApi__pb2.CandidateUpdate.SerializeToString,
            EremApi__pb2.Suggestions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EremApi/setSentence',
            EremApi__pb2.Sentence.SerializeToString,
            EremApi__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EremApi/isReady',
            EremApi__pb2.Void.SerializeToString,
            EremApi__pb2.Ready.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
